
- name: Copying Redis repo 
  ansible.builtin.copy:
     src: redis.repo 
     dest: /etc/yum.repos.d/redis.repo 

- name: Installing Redis
  ansible.builtin.package:
    name: redis-6.2.7
    state: present

- name: Update Redis Config
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0' 

- name: Restarting Service 
  ansible.builtin.service:
    state: started
    name: redis 
    enabled: yes 

- name: Doing set-hostname 
  ansible.builtin.include_role:
    name: common
    tasks_from: set-hostname