- name: Copy MongoDB repo file 
  ansible.builtin.copy:
    src: mongo.repo  
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing MongoDB
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: Update MongoDB Config
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0' 

- name: Starting MongoDB 
  ansible.builtin.service:
    name: mongod 
    state: started
    enabled: yes

- name: Download and extracting mongodb 
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Load Catalogue Schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes
  loop: 
    - catalogue 
    - users

- name: Doing set-hostname 
  ansible.builtin.include_role:
    name: common
    tasks_from: set-hostname