- name: Demo on using vairables 
  hosts: all 
  vars:                            # Play-level variables 
    URL: play.google.com           
  tasks: 
    - name: Printing the URL 
      ansible.builtin.debug:
            msg: Value of URL is {{URL}}

    - name: Printing the URL with space 
      ansible.builtin.debug:
            msg: Value of URL is {{ URL }}

    - name: Printing the URL with quotes 
      ansible.builtin.debug:
            msg: "{{ URL }}" 


# If you just use the variable in the msg :, ensure you quote them.