- name: Demo on conditions 
  hosts: all  
  vars:   
    action: true
    foo: fantastic
  tasks: 
    - name: Run this when os is centos 
      ansible.builtin.debug: 
        msg: Hai from centos  
      when: action

    - name: Run the command if "foo" is defined
      ansible.builtin.shell: echo "I've got '{{ foo }}' and am not afraid to use it!"
      when: foo is defined  # This will be failed as I've not delcared the variable foo 

    - name: Run the command if "foo" is defined
      ansible.builtin.shell: echo "I've got '{{ foo }}' and am not afraid to use it!"
      when: foo is undefined  # This will be failed as I've not delcared the variable foo 