- name: Demo on conditions 
  hosts: all  
  vars:   
    bar: thebestbasr 
  tasks: 
    - name: Run this when os is centos 
      ansible.builtin.debug: 
        msg: Hai from centos  
      when: action is undefined

    - name: Run the command if "foo" is defined
      ansible.builtin.shell: echo "I've got '{{ foo }}' and am not afraid to use it!"
      when: foo is defined  # This will be failed as I've not delcared the variable foo 

    - name: Fail if "bar" is undefined
      ansible.builtin.fail: msg="Bailing out. This play requires 'bar'"
      when: bar is defined # This will be passsed as I've not delcared the variable bar 