- name: Demo on copy 
  hosts: all 
  tasks : 
    - name: Copy file to destination 
      ansible.builtin.copy:
        src: inv 
        dest: /etc/foo.conf
        owner: foo
        group: foo
        mode: '0644'