- name: Installing Nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Download and extract frontend 
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/frontend/archive/main.zip
    dest: /tmp 
    remote_src: yes  # If the source is not local , you need to mention remote soruce as yes. 

- name: Recursively remove directory
  ansible.builtin.file:
    path: /etc/foo
    state: absent

