- name: Configure Yum Repos
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash

- name: Installing RabbitMQ and Dependencies
  ansible.builtin.yum:
    name: 
      - https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh 
      - rabbitmq-server
    state: installed 

- name: Starting RabbitMQ 
  ansible.builtin.systemd:
    state: started
    name: rabbitmq-server 
    enabled: yes 

- name: Adding rabbitmq application user 
  community.rabbitmq.rabbitmq_user:
    user: joe
    password: changeme
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present

