- name: Installing Erlang Yum Repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash

- name: Configure RabbitMQ Repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: Installing RabbitMQ and Dependencies
  ansible.builtin.yum:
    name: rabbitmq-server
    state: installed 

- name: Starting RabbitMQ 
  ansible.builtin.systemd:
    state: restarted
    name: rabbitmq-server 
    enabled: yes 

- name: Adding rabbitmq application user 
  community.rabbitmq.rabbitmq_user:
    user: roboshop 
    password: roboshop123
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present

- name: Doing set-hostname 
  ansible.builtin.include_role:
    name: common
    tasks_from: set-hostname