# This task Updated and restarts logstash config
- name: Copying The logstash config 
  ansible.builtin.template:
    src: logstash.conf 
    dest: /etc/logstash/conf.d/logstash.conf

- name: restarting logstash 
  ansible.builtin.systemd:
    name: logstash  
    daemon_reload: yes
    state: restarted  

# Logstash is a greedy component towards memory and takes times to restart. So, you need to ensure thhat only after the port comes up, we need to consider logstahs startup as success.
- name: Wait forlogstash port to come up 
  ansible.builtin.wait_for:
    port: 5044 
    delay: 60 
    timeout: 90
