- name: Adding Application User 
  ansible.builtin.user:
    name: roboshop 
    comment: roboshop project application user 
  register: APP_USER_INFO

- name: Installing boto3 and botocore needed for aws secret lookup 
  ansible.builtin.pip:
    name: 
      - botocore
      - boto3   
    executable: pip3

