- name: Download and extraing {{COMPONENT}} 
  ansible.builtin.unarchive:
    src: https://github.com/s-robot-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp 
    remote_src: yes  # If the source is not local , you need to mention remote soruce as yes. 
