- name: Deleting Old Content
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent  

- name: Download and extraing {{COMPONENT}} 
  ansible.builtin.unarchive:
    src: http://172.31.2.247:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: /home/roboshop/{{COMPONENT}}/ 
    remote_src: yes  # If the source is not local , you need to mention remote soruce as yes. 


